# This file was generated by nvfetcher, please do not modify it manually.
{
  fetchgit,
  fetchurl,
  fetchFromGitHub,
  dockerTools,
}:
{
  rofi-themes = {
    pname = "rofi-themes";
    version = "512a585fff6da5b2a90e5948059b062516ddb2e7";
    src = fetchFromGitHub {
      owner = "adi1090x";
      repo = "rofi";
      rev = "512a585fff6da5b2a90e5948059b062516ddb2e7";
      fetchSubmodules = false;
      sha256 = "sha256-iUX0Quae06tGd7gDgXZo1B3KYgPHU+ADPBrowHlv02A=";
    };
    date = "2026-05-31";
  };
}
