# This file was generated by nvfetcher, please do not modify it manually.
{
  fetchgit,
  fetchurl,
  fetchFromGitHub,
  dockerTools,
}:
{
  hyprcursor = {
    pname = "hyprcursor";
    version = "b62396457b9cfe2ebf24fe05404b09d2a40f8ed7";
    src = fetchFromGitHub {
      owner = "hyprwm";
      repo = "hyprcursor";
      rev = "b62396457b9cfe2ebf24fe05404b09d2a40f8ed7";
      fetchSubmodules = false;
      sha256 = "sha256-pVICsV7FtcEeVwg5y/LFh3XFUkVJninm/P1j/JHzEbM=";
    };
    date = "2026-03-02";
  };
  hyprlock = {
    pname = "hyprlock";
    version = "768ade88a8a8b79acdec4b7cc92a32cbc4cdae19";
    src = fetchFromGitHub {
      owner = "hyprwm";
      repo = "hyprlock";
      rev = "768ade88a8a8b79acdec4b7cc92a32cbc4cdae19";
      fetchSubmodules = false;
      sha256 = "sha256-1PEKXrIfc4qIDo6Ut1D3aK2dK3HRnIso2SPopKNN2nA=";
    };
    date = "2026-03-23";
  };
  swww = {
    pname = "swww";
    version = "432b7135af0bb34e4b0e55edf76ff516937bc7b0";
    src = fetchFromGitHub {
      owner = "LGFae";
      repo = "swww";
      rev = "432b7135af0bb34e4b0e55edf76ff516937bc7b0";
      fetchSubmodules = false;
      sha256 = "sha256-pX6fJrlNXe1W5ZO9nC9ikN1zoAcHDqErLS7EnglD33o=";
    };
  };
  wallust = {
    pname = "wallust";
    version = "27c0170a338079832350a130c7736f3a0d93c87f";
    src = fetchgit {
      url = "https://codeberg.org/explosion-mental/wallust.git";
      rev = "27c0170a338079832350a130c7736f3a0d93c87f";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-AMyLJnompF/MfXyollyYXE7Ll/P6nclB6YhfOcsboMw=";
    };
    date = "2026-03-26";
  };
}
