# This file was generated by nvfetcher, please do not modify it manually.
{
  fetchgit,
  fetchurl,
  fetchFromGitHub,
  dockerTools,
}:
{
  hyprcursor = {
    pname = "hyprcursor";
    version = "39435900785d0c560c6ae8777d29f28617d031ef";
    src = fetchFromGitHub {
      owner = "hyprwm";
      repo = "hyprcursor";
      rev = "39435900785d0c560c6ae8777d29f28617d031ef";
      fetchSubmodules = false;
      sha256 = "sha256-fCpwFiTW0rT7oKJqr3cqHMnkwypSwQKpbtUEtxdkgrM=";
    };
    date = "2026-04-18";
  };
  hyprlock = {
    pname = "hyprlock";
    version = "c72fd24ca70bf726bbb58609b37545b24dcc9810";
    src = fetchFromGitHub {
      owner = "hyprwm";
      repo = "hyprlock";
      rev = "c72fd24ca70bf726bbb58609b37545b24dcc9810";
      fetchSubmodules = false;
      sha256 = "sha256-v7zsCPK3yinSYJmZfOll7rtGo9g02a7ulmS/loFa0h0=";
    };
    date = "2026-06-24";
  };
  swww = {
    pname = "swww";
    version = "432b7135af0bb34e4b0e55edf76ff516937bc7b0";
    src = fetchFromGitHub {
      owner = "LGFae";
      repo = "swww";
      rev = "432b7135af0bb34e4b0e55edf76ff516937bc7b0";
      fetchSubmodules = false;
      sha256 = "sha256-pX6fJrlNXe1W5ZO9nC9ikN1zoAcHDqErLS7EnglD33o=";
    };
  };
  wallust = {
    pname = "wallust";
    version = "e56187e965079f9145a4f5917b306b680f946420";
    src = fetchgit {
      url = "https://codeberg.org/explosion-mental/wallust.git";
      rev = "e56187e965079f9145a4f5917b306b680f946420";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-V8spRG7kzZPvACxM50uimdSFkWquaZ5wK6ZIfkPiaME=";
    };
    date = "2026-06-14";
  };
}
