# This file was generated by nvfetcher, please do not modify it manually.
{
  fetchgit,
  fetchurl,
  fetchFromGitHub,
  dockerTools,
}:
{
  sysmocap = {
    pname = "sysmocap";
    version = "v0.8.0";
    src = fetchFromGitHub {
      owner = "xianfei";
      repo = "SysMocap";
      rev = "v0.8.0";
      fetchSubmodules = false;
      sha256 = "sha256-v1sY6c9rda4crD4+EyNrezCm0fUuVt14cJluYKITS+c=";
    };
  };
}
