# This file was generated by nvfetcher, please do not modify it manually.
{
  fetchgit,
  fetchurl,
  fetchFromGitHub,
  dockerTools,
}:
{
  csakura = {
    pname = "csakura";
    version = "9664fcb";
    src = fetchFromGitHub {
      owner = "realstrawhat";
      repo = "csakura";
      rev = "9664fcbffac096acdb44cbc8c81527fb57d13639";
      fetchSubmodules = false;
      sha256 = "sha256-xDN0o48GdJY8wFxSNdB5NxlH3rD4sBzUJopJagrhQbY=";
    };
    date = "2026-07-17";
  };
}
